apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ec-mongodb-pvc-sc-nas2
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: alibabacloud-cnfs-nas
