apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-deadline
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      activeDeadlineSeconds: 10
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job