apiVersion: v1
kind: ReplicationController
metadata:
  name: ec-rc-kubia
spec:
  replicas: 5
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: ec-c-kubia
          image: luksa/kubia
          ports:
            - containerPort: 8080