apiVersion: v1
kind: Pod
metadata:
  name: ec-pod-kubia-unhealthy
spec:
  containers:
    - name: ec-c-kubia-unhealthy
      image: luksa/kubia-unhealthy
      livenessProbe:
        httpGet:
          path: /
          port: 8080