apiVersion: v1
kind: Pod
metadata:
  name: ec-requests-pod-3
spec:
  containers:
    - name: main
      image: busybox
      command: ["dd", "if=/dev/zero", "of=/dev/null"]
      resources:
        requests:
          cpu: 64
          memory: 20Mi