apiVersion: v1
kind: Pod
metadata:
  name: foosapod
spec:
  serviceAccount: foo
  containers:
    - name: ec-main
      image: curlimages/curl
      command: ["sleep","99999999"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2