apiVersion: v1
kind: Pod
metadata:
  name: ec-pod-kubia-labels
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: luksa/kubia
    name: ec-c-kubia-labels
    ports: 
    - containerPort: 8080
      protocol: TCP