apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ec-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: ec-pod-kubia
          image: luksa/kubia
          readinessProbe:
            exec:
              command:
                - ls
                - /var/ready
          ports:
            - containerPort: 8080
    