apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-c
        image: busybox
        command: ["/bin/sleep", "99999"]
      tolerations:
      - key: node-type
        operator: Equal
        value: production
        effect: NoSchedule